name: "Chore: ABAPlint check"
on:
  push:
    branches:
      - main
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: abaplint
        uses: abaplint/actions-abaplint@main
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}       
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
